jobs:
- job: CoreML_CI
  workspace:
    clean: all
  pool:
    vmImage: 'macOS-12'
  variables:
    MACOSX_DEPLOYMENT_TARGET: '10.14'
    TODAY: $[format('{0:dd}{0:MM}{0:yyyy}', pipeline.startTime)]
  timeoutInMinutes: 120
  steps:
  - script: brew install coreutils ninja
    displayName: Install coreutils and ninja

  - script: |
      brew install ccache
      echo "##vso[task.prependpath]/usr/local/opt/ccache/libexec"
    displayName: Install ccache and update PATH to use linked versions of gcc, cc, etc

  - task: Cache@2
    inputs:
      key:  ' "$(TODAY)" | coreml | "$(Build.SourceVersion)" '
      path: $(Pipeline.Workspace)/ccache
      restoreKeys: |
        "$(TODAY)" | coreml
    displayName: ccache task

  - script: |
      python3 tools/ci_build/build.py \
      --build_dir build \
      --skip_submodule_sync \
      --cmake_generator=Ninja \
      --parallel \
      --build_shared_lib \
      --config Debug \
      --use_cache \
      --use_coreml
    env:
      CCACHE_COMPILERCHECK: content
      CCACHE_DIR: $(Pipeline.Workspace)/ccache
    displayName: CoreML EP, Build and Test on macOS

  - script: |
      ccache -s
      ccache -z
      ls -l $(CCACHE_DIR)
      du -sh $(CCACHE_DIR)
    displayName: Show Cache stats and Clear stats.
